// Run the `noir_tracer_wasm` module in a bare WebAssembly engine.
//
//   node run_wasm.mjs <module.wasm> <artifact.json> <Prover.toml>
//
// Prints the trace JSON on stdout. Uses only `WebAssembly.instantiate` and the
// `ct_*` C-ABI exports -- no wasm-bindgen glue, no JS shim generated by
// `wasm-bindgen-cli`. The handful of `__wbindgen_*` imports the module still
// declares come from `getrandom`'s `wasm_js` backend; they are stubbed to throw
// here, which is safe precisely because the tracing path never reaches them --
// if that ever changed, this script would fail loudly rather than silently.

import { readFileSync } from 'node:fs';

const [, , wasmPath, artifactPath, inputsPath] = process.argv;
if (!wasmPath || !artifactPath || !inputsPath) {
  console.error('usage: node run_wasm.mjs <module.wasm> <artifact.json> <Prover.toml>');
  process.exit(2);
}

const unreachable = (name) => () => {
  throw new Error(`the traced program reached ${name}, which this host does not provide`);
};

const bytes = readFileSync(wasmPath);
const module = await WebAssembly.compile(bytes);

// Satisfy whatever the module declares, without pretending to implement it.
const imports = {};
for (const { module: m, name } of WebAssembly.Module.imports(module)) {
  imports[m] ??= {};
  imports[m][name] = unreachable(`${m}.${name}`);
}

const { exports } = await WebAssembly.instantiate(module, imports);
const memory = exports.memory;

function put(str) {
  const encoded = new TextEncoder().encode(str);
  const ptr = exports.ct_alloc(encoded.length);
  new Uint8Array(memory.buffer, ptr, encoded.length).set(encoded);
  return [ptr, encoded.length];
}

const [artifactPtr, artifactLen] = put(readFileSync(artifactPath, 'utf8'));
const [inputsPtr, inputsLen] = put(readFileSync(inputsPath, 'utf8'));

const resultPtr = exports.ct_trace(artifactPtr, artifactLen, inputsPtr, inputsLen, 0);
const resultLen = exports.ct_result_len();
const isError = exports.ct_result_is_error() !== 0;
const result = new TextDecoder().decode(
  new Uint8Array(memory.buffer, resultPtr, resultLen).slice(),
);

exports.ct_free(resultPtr, resultLen);
exports.ct_free(artifactPtr, artifactLen);
exports.ct_free(inputsPtr, inputsLen);

if (isError) {
  console.error(`tracing failed inside wasm: ${result}`);
  process.exit(1);
}
process.stdout.write(result);
